exclude: 'docs|assets'

default_language_version:
    python: python3

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
      - id: clang-format

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
      - id: black
        language_version: python3.8

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.2
      hooks:
      - id: codespell
        args: [
              '--ignore-words-list=reord,dout,nd,te,ser',  # Word used in error messages that need rewording
              --check-filenames,
              --check-hidden,
          ]
